/** @noSelfInFile **/

declare namespace eventHandler {
    export function OnPlayerConnect(pid: any, playerName: any): any;
    export function OnPlayerDisconnect(pid: any): any;
    export function OnGUIAction(pid: any, idGui: any, data: any): boolean;
    export function OnPlayerSendMessage(pid: any, message: any): any;
    export function OnPlayerDeath(pid: any): any;
    export function OnDeathTimeExpiration(pid: any): any;
    export function OnPlayerAttribute(pid: any): any;
    export function OnPlayerSkill(pid: any): any;
    export function OnPlayerLevel(pid: any): any;
    export function OnPlayerShapeshift(pid: any): any;
    export function OnPlayerCellChange(pid: any): any;
    export function OnPlayerEndCharGen(pid: any): any;
    export function OnPlayerEquipment(pid: any): any;
    export function OnPlayerInventory(pid: any): any;
    export function OnPlayerSpellbook(pid: any): any;
    export function OnPlayerQuickKeys(pid: any): any;
    export function OnPlayerJournal(pid: any): any;
    export function OnPlayerFaction(pid: any): any;
    export function OnPlayerTopic(pid: any): any;
    export function OnPlayerBounty(pid: any): any;
    export function OnPlayerReputation(pid: any): any;
    export function OnPlayerBook(pid: any): any;
    export function OnPlayerItemUse(pid: any): any;
    export function OnPlayerMiscellaneous(pid: any): any;
    export function OnCellLoad(pid: any, cellDescription: any): any;
    export function OnCellUnload(pid: any, cellDescription: any): any;
    export function OnCellDeletion(cellDescription: any): any;
    export function OnActorList(pid: any, cellDescription: any): any;
    export function OnActorEquipment(pid: any, cellDescription: any): any;
    export function OnActorAI(pid: any, cellDescription: any): any;
    export function OnActorDeath(pid: any, cellDescription: any): any;
    export function OnActorCellChange(pid: any, cellDescription: any): any;
    export function OnObjectActivate(pid: any, cellDescription: any): any;
    export function OnObjectPlace(pid: any, cellDescription: any): any;
    export function OnObjectSpawn(pid: any, cellDescription: any): any;
    export function OnObjectDelete(pid: any, cellDescription: any): any;
    export function OnObjectLock(pid: any, cellDescription: any): any;
    export function OnObjectTrap(pid: any, cellDescription: any): any;
    export function OnObjectScale(pid: any, cellDescription: any): any;
    export function OnObjectState(pid: any, cellDescription: any): any;
    export function OnDoorState(pid: any, cellDescription: any): any;
    export function OnContainer(pid: any, cellDescription: any): any;
    export function OnVideoPlay(pid: any): any;
    export function OnRecordDynamic(pid: any): any;
    export function OnWorldKillCount(pid: any): any;
    export function OnWorldMap(pid: any): any;
    export function OnWorldWeather(pid: any): any;
    export function OnMpNumIncrement(currentMpNum: any): any;
    export function OnObjectLoopTimeExpiration(loopIndex: any): any;
}
